In [ ]:
Make a 4*3*2 matrix (NumPy array) containing linearly spaced integers between 100 and 1000.



In [43]:
a=np.linspace(100,1000,24)
a

array([ 100.        ,  139.13043478,  178.26086957,  217.39130435,
        256.52173913,  295.65217391,  334.7826087 ,  373.91304348,
        413.04347826,  452.17391304,  491.30434783,  530.43478261,
        569.56521739,  608.69565217,  647.82608696,  686.95652174,
        726.08695652,  765.2173913 ,  804.34782609,  843.47826087,
        882.60869565,  921.73913043,  960.86956522, 1000.        ])

In [44]:
d=a.reshape((4,3,2))
d

array([[[ 100.        ,  139.13043478],
        [ 178.26086957,  217.39130435],
        [ 256.52173913,  295.65217391]],

       [[ 334.7826087 ,  373.91304348],
        [ 413.04347826,  452.17391304],
        [ 491.30434783,  530.43478261]],

       [[ 569.56521739,  608.69565217],
        [ 647.82608696,  686.95652174],
        [ 726.08695652,  765.2173913 ]],

       [[ 804.34782609,  843.47826087],
        [ 882.60869565,  921.73913043],
        [ 960.86956522, 1000.        ]]])

In [ ]:
Print all columns except the first and the last in the above matrix. 


In [45]:
d[::][1:3]

array([[[334.7826087 , 373.91304348],
        [413.04347826, 452.17391304],
        [491.30434783, 530.43478261]],

       [[569.56521739, 608.69565217],
        [647.82608696, 686.95652174],
        [726.08695652, 765.2173913 ]]])

In [ ]:
Find the median of the above-generated 4*3*2 matrix along the columns


In [46]:
np.median(d,axis=0)

array([[452.17391304, 491.30434783],
       [530.43478261, 569.56521739],
       [608.69565217, 647.82608696]])

In [ ]:
Make another 2*4 matrix containing only elements from the above matrix, which are between 400 and 750.


In [47]:
b=a[(a>400)&(a<750)]
b

array([413.04347826, 452.17391304, 491.30434783, 530.43478261,
       569.56521739, 608.69565217, 647.82608696, 686.95652174,
       726.08695652])

In [48]:
c=b[0:8].reshape((2,4))
c

array([[413.04347826, 452.17391304, 491.30434783, 530.43478261],
       [569.56521739, 608.69565217, 647.82608696, 686.95652174]])

In [ ]:
Print the sum of all the rows in the above 2*4 matrix.
(Note: Kindly print only, do not overwrite the matrix.)


In [50]:
np.sum(c,axis=1)

array([1886.95652174, 2513.04347826])

In [ ]:
Create a 4*5 array with 1 on the border and 0 inside

In [34]:
d=np.zeros((4,5),dtype=int)
d

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [35]:
d[0][0]=1
d[0][4]=1
d[3][0]=1
d[3][4]=1
d

array([[1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 1]])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [2]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [3]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [4]:
mat[3][-1]

20

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [5]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [6]:
mat[-1]

array([21, 22, 23, 24, 25])

In [ ]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [8]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [9]:
np.sum(mat)

325

#### Get the standard deviation of the values in mat

In [13]:
np.std(mat)

7.211102550927978

#### Get the sum of all the columns in mat

In [10]:
np.sum(mat,axis=0)

array([55, 60, 65, 70, 75])

# Great Job!